### ISSUE TITLE
Mixin crash on startup for Forge 1.18.2

### ISSUE THREAD

**Issue by Raidobw2** [Siuolthepic/Soul-Ice#6]
Hi again! It looks like there's a small startup bug maybe due to mixins for Forge. I'm using Forge `40.1.20` for Minecraft `1.18.2`.
The entirety of the mods folder is only composed of `soulice-1.3.0+1.18.2-forge.jar`, attached is the game log which should contain the important information:
https://paste.feed-the-beast.com/view/8e11001b

Thank you very much in advance for your help!

**Comment by Siuolplex** [comment]
I have a feeling this issue is related to mapping stuff.

If so, oh god.

For now, Ima confirm this on my machine, and if its a thing, Ill temporarily take down the Forge version until I can post a working version I need to shower then sleep then go to school so its gonna be another 16 hours for this to get fixed

**Comment by Siuolplex** [comment]
Update: Looking at it further, it may be an extra line that I included on accident, gonna see if it boots without that and if so Ill be sending an update out in 20 minutes

**Comment by Siuolplex** [comment]
Just realized this is technically https://github.com/architectury/architectury-loom/issues/85. Ill need to compile on a version with a fix. For now, Ill pull the Forge version of the update off of Modrinth and Curseforge until a fix is released.

**Comment by Siuolplex** [comment]
Alright, I found a work around, Ill be publishing an emergency 1.3.1 for Forge exclusively, found some more bugs as well, Ill wait til after school for those, thank you for your help

**Comment by Raidobw2** [comment]
No worries, take your time!  I'm already grateful when developers take their own time to make two release versions, since it's a lot of extra work to get it working both for Forge and Fabric. Thanks for the information again and have a good day 😄

**Comment by Siuolplex** [comment]
Technically 3 as I work on a Quilt version that ends up on Modrinth only for now until Curseforge adds Quilt support. :)

But NP, I only wanted to get this out so its playable on Forge again, and then Ill fix bugs from here. Hopefully by this time tomorrow Soul Ice is the most bug free mod yet!

**Comment by Raidobw2** [comment]
Hi again, I've been able to test the issue today with the hotfix and I can confirm that it works fully, and I can open backpacks, etc. Thank you a lot! One of my colleagues was then able to see your mod and the pastel colored planks grabbed their attention :) I'll try and put that content to good use, you can close this issue as solved, cheers

**Comment by Siuolplex** [comment]
Will do, thanks for the report!
