### ISSUE TITLE
Suggestion: Orange Rose would need a hitbox and use

### ISSUE THREAD

**Issue by Raidobw2** [Siuolthepic/Soul-Ice#7]
It looks like the feature is still WIP but the Orange Rose would need a pass through hitbox and a use in-game
![image](https://user-images.githubusercontent.com/17010632/170351838-f1f10eb1-8166-447d-8592-ca7788cbc37f.png)
`soulice-1.3.2+1.18.2-forge.jar`
The generation of that feature for now can be disabled by mods such as KubeJS

**Comment by Siuolplex** [comment]
I have successfully done that, thanks for the report
