### ISSUE TITLE
Boat spins very fast on water

### ISSUE THREAD

**Issue by Raidobw2** [Siuolthepic/Soul-Ice#8]
Hi, it looks like the boat's velocity never stops when on land/soul ice, I've made some videos to explain it:

https://user-images.githubusercontent.com/17010632/170354461-adfdc058-01ea-49fe-a535-7bf891a06285.mp4

https://user-images.githubusercontent.com/17010632/170354474-197a6bfc-61aa-43b2-8053-b44d0b596926.mp4

It looks like that also happens in water, although since that's not on land (and therefore uncapped), the speed can be infinite:

https://user-images.githubusercontent.com/17010632/170354593-098659d6-5d5d-4bf6-9bb8-820475607f50.mp4

On land such as cobblestone or dirt, and in water, this makes it difficult to control the boat since it will keep turning as you go forward.

I think this is where the magic happens:

https://github.com/Siuolthepic/Soul-Ice/blob/1f5f649999f126f85a07ce3c3ed27d2dc3157b02/common/src/main/java/io/siuolplex/soul_ice/mixin/BoatEntityMixin.java#L15-L23

I would like to suggest potentially only affecting boats on soul ice and/or any ice, giving them a higher spin time, but making sure that this yaw speed decays over time (even if it's by a tiny amount)

Or perhaps if the purpose was to enable people to make tricks in the air while sliding on ice with boats, then possibly the CTRL key could be used a boost key to allow the boat to rotate quickly in the air in a specific direction. That way you could leave the boat's mechanics normal (allowing for easier control) and then use the boost for tricks. Say you'd be rotating left in the air, then pressing CTRL would make your boat do a quick 360 or something, or raise it's rotation speed limit for a short amount of time

Thanks in advance for looking into this bug/suggestion!

Mod version:
`soulice-1.3.2+1.18.2-forge.jar`

**Comment by Siuolplex** [comment]
Ummmmm

Sorry for late response, but try the newest version...

How did this end up happening... I must of forgotten a check

**Comment by Siuolplex** [comment]
Yeah now that I think about it I believe the newest version fixes it as we use a mixin courtesy of PeculiarPieces. 

I'll leave this open til I can test later today

**Comment by Raidobw2** [comment]
I can have a proper test with it as well in a few hours when I get to it, thanks a bunch for the fixes so far!

**Comment by Siuolplex** [comment]
Assuming this is good, I'll close it down.

**Comment by Raidobw2** [comment]
I was just about to comment since I just got to test it, sorry for the late response! The boat on land and water works as normal, the boat on ice is spinning good too! The boat on soul ice spins very fast and has a bit of a quirk where if you hold left for a bit and then try to stop momentum with the right key, you can't. But with Jumpy Boats installed you can jump and that helps resetting the momentum. I'm happy with your fixes, thanks a lot and have a great weekend!
